create table if not exists public.licenses (
    id bigint generated by default as identity primary key,
    license_key text unique not null,
    device_id text,
    is_active boolean not null default true,
    activated_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.licenses enable row level security;

insert into public.licenses (license_key)
select 'GREEG-' || generate_series(1, 1000)
on conflict (license_key) do nothing;
